### ISSUE TITLE
Wrong registration field name

### ISSUE THREAD

**Issue by P-CAST** [R-comp/Fjango#1]
In register page, Username field showing error like it is Email field
![field_error](https://user-images.githubusercontent.com/68631076/141687734-c9ff34cb-93f6-457c-9bd0-171a9da77f60.png)

Solution: change field type

**Comment by R-comp** [comment]
> In register page, Username field showing error like it is Email field ![field_error](https://user-images.githubusercontent.com/68631076/141687734-c9ff34cb-93f6-457c-9bd0-171a9da77f60.png)
> 
> Solution: change field type

**Comment by R-comp** [comment]
> In register page, Username field showing error like it is Email field ![field_error](https://user-images.githubusercontent.com/68631076/141687734-c9ff34cb-93f6-457c-9bd0-171a9da77f60.png)
> 
> Solution: change field type
